---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    grafana.internal/instance: grafana
spec:
  external:
    url: https://grafana.cloud.witl.xyz
    apiKey:
      name: grafana-cloud-operator
      key: token
