---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lan-icmp
spec:
  module: icmp
  prober:
    url: blackbox-exporter-lan.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - nas.286k.co
        - unifi.286k.co
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-lan
      action: replace
