---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "sabnzbd-dst"
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-1gb
  restic:
    repository: "sabnzbd-volsync-r2-secret"
    copyMethod: Snapshot
    volumeSnapshotClassName: "csi-ceph-blockpool"
    cacheStorageClassName: "ceph-block"
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: "10Gi"
    storageClassName: "ceph-block"
    accessModes: ["ReadWriteOnce"]
    capacity: "1Gi"
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "sabnzbd-volsync-r2"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "sabnzbd-volsync-r2-secret"
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .REPOSITORY_TEMPLATE }}/sabnzbd"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync-r2-template
