---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: downforacrossbot
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: downforacrossbot-secret
    template:
      engineVersion: v2
      data:
        config.json: |
          {
            "clientId": {{ .DOWNFORACROSSBOT_CLIENT_ID | quote }},
            "guildId": {{ .DOWNFORACROSSBOT_GUILD_ID | quote }},
            "token": {{ .DOWNFORACROSSBOT_DISCORD_TOKEN | quote }}
          }
  dataFrom:
    - extract:
        key: downforacrossbot
