---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: observability-m2m
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: observability-m2m
    template:
      engineVersion: v2
      data:
        client_id: "{{ trim .client_id }}"
        client_secret: "{{ trim .client_secret }}"
  dataFrom:
    - extract:
        key: observability-m2m
