---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
spec:
  chartRef:
    kind: OCIRepository
    name: k8s-monitoring
  interval: 1h
  values:
    cluster:
      name: "kyak"
    destinations:
      loki:
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
      mimir:
        type: otlp
        url: https://mimir.cloud.witl.xyz/otlp
        protocol: http
        metrics: { enabled: true }
        logs:    { enabled: true }
        traces:  { enabled: true }
        auth:
          type: oauth2
          oauth2:
            tokenURL: "https://sso-3da0e7d4.sso.duosecurity.com/oauth/DIV21P82KMG9NOTNQW6J/token"
            clientIdFrom: string.trim_space(local.file.mimir_client_id.content)
            clientSecretFile: /var/run/secrets/mimir-oauth/clientSecret
            scopes:
              - mimir:write
            endpointParams:
              grant_type: ["client_credentials"]
    #
    # Features
    #
    clusterMetrics:
      enabled: true
      collector: alloy-metrics
    hostMetrics:
      enabled: true
      collector: alloy-metrics
      nodeLabels:
        nodePool: true
        region: true
        availabilityZone: true
        nodeRole: true
        nodeOS: true
        nodeArchitecture: true
        instanceType: true
      linuxHosts:
        enabled: true
      energyMetrics:
        enabled: true
    clusterEvents:
      enabled: true
      collector: alloy-singleton
    nodeLogs:
      enabled: false
    podLogsViaKubernetesApi:
      enabled: true
      collector: alloy-logs
      nodeLabels:
        nodePool: true
        region: true
        availabilityZone: true
        nodeRole: true
        nodeOS: true
        nodeArchitecture: true
        instanceType: true
      structuredMetadata:
        node_pool: nodepool
        region: region
        availability_zone: availability_zone
        node_role: node_role
        node_os: os
        node_arch: architecture
        node_type: instance_type
    applicationObservability:
      enabled: false
      receivers:
        otlp:
          grpc:
            enabled: true
            port: 4317
          http:
            enabled: true
            port: 4318
        zipkin:
          enabled: true
          port: 9411
    autoInstrumentation:
      enabled: false
    annotationAutodiscovery:
      enabled: true
      collector: alloy-metrics
      nodeLabels:
        nodePool: true
        region: true
        availabilityZone: true
        nodeRole: true
        nodeOS: true
        nodeArchitecture: true
        instanceType: true
    prometheusOperatorObjects:
      enabled: true
      collector: alloy-metrics
    profiling:
      enabled: false
    integrations:
      collector: alloy-metrics
      cert-manager:
        instances:
          - name: cert-manager
            namespace: cert-manager
            labelSelectors:
              app.kubernetes.io/name: cert-manager
      alloy:
        instances:
          - name: alloy
            labelSelectors:
              app.kubernetes.io/name:
                - alloy-metrics
                - alloy-singleton
                - alloy-logs
                - alloy-receiver
                - alloy-profiles
    selfReporting:
      enabled: false
      destinations: []
      scrapeInterval: ""
    collectors:
      alloy-metrics:
        presets: [clustered, statefulset]
        extraConfig: |-
          local.file "mimir_client_id" {
            filename = "/var/run/secrets/mimir-oauth/clientId"
          }
        alloy:
          storagePath: /var/lib/alloy
          mounts:
            extra:
              - name: alloy-wal
                mountPath: /var/lib/alloy
              - name: mimir-oauth
                mountPath: /var/run/secrets/mimir-oauth
                readOnly: true
        controller:
          enableStatefulSetAutoDeletePVC: true
          volumeClaimTemplates:
            - metadata:
                name: alloy-wal
              spec:
                accessModes: ["ReadWriteOnce"]
                storageClassName: "ceph-block"
                resources:
                  requests:
                    storage: 5Gi
          volumes:
            extra:
              - name: mimir-oauth
                secret:
                  secretName: mimirwriteoauth
      alloy-singleton:
        presets: [singleton]
        extraConfig: |-
          local.file "mimir_client_id" {
            filename = "/var/run/secrets/mimir-oauth/clientId"
          }
          local.file "alertmanager_global" {
            filename = "/etc/alloy/alertmanager-global/config"
          }
          mimir.rules.kubernetes "mimir" {
            address       = "https://mimir.cloud.witl.xyz"
            sync_interval = "2m"
            oauth2 {
              token_url           = "https://sso-3da0e7d4.sso.duosecurity.com/oauth/DIV21P82KMG9NOTNQW6J/token"
              client_id           = string.trim_space(local.file.mimir_client_id.content)
              client_secret_file  = "/var/run/secrets/mimir-oauth/clientSecret"
              scopes              = ["mimir:write", "mimir:read"]
              endpoint_params     = { "grant_type" = "client_credentials" }
            }
          }
          mimir.alerts.kubernetes "mimir" {
            address       = "https://mimir.cloud.witl.xyz"
            global_config = local.file.alertmanager_global.content
            sync_interval = "2m"
            oauth2 {
              token_url           = "https://sso-3da0e7d4.sso.duosecurity.com/oauth/DIV21P82KMG9NOTNQW6J/token"
              client_id           = string.trim_space(local.file.mimir_client_id.content)
              client_secret_file  = "/var/run/secrets/mimir-oauth/clientSecret"
              scopes              = ["mimir:write", "mimir:read"]
              endpoint_params     = { "grant_type" = "client_credentials" }
            }
          }
        alloy:
          stabilityLevel: experimental
          mounts:
            extra:
              - name: mimir-oauth
                mountPath: /var/run/secrets/mimir-oauth
                readOnly: true
              - name: alertmanager-global
                mountPath: /etc/alloy/alertmanager-global
                readOnly: true
        controller:
          volumes:
            extra:
              - name: mimir-oauth
                secret:
                  secretName: mimirwriteoauth
              - name: alertmanager-global
                secret:
                  secretName: alertmanager-global-config
      alloy-logs:
        presets: [clustered, daemonset]
        alloy:
          storagePath: /var/lib/alloy
          mounts:
            extra:
              - name: alloy-log-positions
                mountPath: /var/lib/alloy
        controller:
          volumes:
            extra:
              - name: alloy-log-positions
                hostPath:
                  path: /var/alloy-log-storage
                  type: DirectoryOrCreate
    telemetryServices:
      kube-state-metrics:
        deploy: true
      node-exporter:
        deploy: true
      kepler:
        deploy: true
