{
 "title": "Space Engineers Server",
 "tags": [
  "prometheus",
  "space"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": { "query": "label_values(server)" } }
  ]
 },
 "panels": [
  {
   "title": "Online Players",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "players_count{server=\"$server\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Planets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "planets_count{server=\"$server\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Grids",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "total_grids{server=\"$server\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Asteroids",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "total_asteroids{server=\"$server\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "server_game_uptime_seconds{server=\"$server\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Trash",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "total_floating_objects{server=\"$server\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "PCU Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "total_pcu_used{server=\"$server\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Pirate PCU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pirate_total_pcu_used{server=\"$server\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Server Ready Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "server_is_ready{server=\"$server\"}",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Simulation CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "simulation_cpu_load{server=\"$server\"}",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "AVG Players Ping",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(player_ping{server=\"$server\"}) by (player_name)",
     "legendFormat": "{{ player_name }}"
    }
   ]
  },
  {
   "title": "Kicked/Banned Players",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "total_banned_players{server=\"$server\"}",
     "legendFormat": "banned"
    },
    {
     "expr": "total_kicked_players{job=\"space-engineers\"}",
     "legendFormat": "kicked"
    }
   ]
  },
  {
   "title": "Simulation Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "simulation_speed{server=\"$server\"}",
     "legendFormat": "{{ server }}"
    }
   ]
  }
 ]
}